# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: currency_converter.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'currency_converter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63urrency_converter.proto\"U\n\x11\x43onversionRequest\x12\x17\n\x0fsource_currency\x18\x01 \x01(\t\x12\x17\n\x0ftarget_currency\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\"M\n\x12\x43onversionResponse\x12\x0c\n\x04rate\x18\x01 \x01(\x01\x12\x18\n\x10\x63onverted_amount\x18\x02 \x01(\x01\x12\x0f\n\x07message\x18\x03 \x01(\t2G\n\x11\x43urrencyConverter\x12\x32\n\x07\x43onvert\x12\x12.ConversionRequest\x1a\x13.ConversionResponseB2\n\x16\x63om.currency.converterB\x16\x43urrencyConverterProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'currency_converter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.currency.converterB\026CurrencyConverterProtoP\001'
  _globals['_CONVERSIONREQUEST']._serialized_start=28
  _globals['_CONVERSIONREQUEST']._serialized_end=113
  _globals['_CONVERSIONRESPONSE']._serialized_start=115
  _globals['_CONVERSIONRESPONSE']._serialized_end=192
  _globals['_CURRENCYCONVERTER']._serialized_start=194
  _globals['_CURRENCYCONVERTER']._serialized_end=265
# @@protoc_insertion_point(module_scope)
